### ISSUE TITLE
On "Player Profiles" page, add a new column for total races

### ISSUE THREAD

**Issue by Zamiell** [Zamiell/isaac-racing-server#10]

**Comment by sillypears** [comment]
Seems like a kind of duplicate of #17, will incorporate this with that.

**Comment by Zamiell** [comment]
its not a dupe.

this issue is for: https://isaacracing.net/profiles

issue #17 is for:  https://isaacracing.net/profile/dea1h

**Comment by sillypears** [comment]
Done 66406189b9739165cc4c68acc4bf7a40a6c6e443
