### ISSUE TITLE
set min-width for forfeit rate

### ISSUE THREAD

**Issue by Zamiell** [Zamiell/isaac-racing-server#19]
so that it doesn't wrap to a second row. although it might mess something else up? dunno

**Comment by sillypears** [comment]
I just use 'no-wrap' instead of min-width for the relevant `<td>` so it auto-sets the width.

**Comment by Zamiell** [comment]
nice

**Comment by sillypears** [comment]
Fixed with commit 00134ce6f40c0dd4359045d6e97ad4994d7d74a7
