### ISSUE TITLE
On profile page, adding spacing

### ISSUE THREAD

**Issue by Zamiell** [Zamiell/isaac-racing-server#30]
![image](https://user-images.githubusercontent.com/5511220/32207806-ca2554fe-bdd4-11e7-9cf9-1d5976367b20.png)

This looks bad. Add some spacing between the title and the end of the previous white thing.

**Comment by Zamiell** [comment]
![image](https://user-images.githubusercontent.com/5511220/32207913-7ab053fa-bdd5-11e7-9d05-ae3414526b81.png)

It should be the SAME amount of spacing here. So make more spacing on the bottom one, and then replicate this to the place of the screenshot in the OP.

**Comment by sillypears** [comment]
I sure hope this one is finally finished.

**Comment by sillypears** [comment]
I think I fixed this one too.
