### ISSUE TITLE
On /races, combine Ranked/Format/Character/Goal in an elegant way

### ISSUE THREAD

**Issue by Zamiell** [Zamiell/isaac-racing-server#31]
This also needs to be on whenever a race row is shown i.e. /profile/Zamiel

Format is the most important column. So I think it is best to change the column header to "Ruleset", and then show the format icon (Seeded/Unseeded/Diversity), and hover over that to reveal a tooltip that gives all of the additional information.

**Comment by sillypears** [comment]
Rabble rabble rabble

bb6050688331b85d9ec029d697c5a73df9f51aa3
