### ISSUE TITLE
Race Listing page overflows bottom navigation buttons

### ISSUE THREAD

**Issue by MacND** [Zamiell/isaac-racing-server#45]
My Chrome window was snapped to a half-screen width but the issue persists regardless of window size.  

![image](https://user-images.githubusercontent.com/13189764/36342117-6b1af70c-13f1-11e8-9205-fe6d876e1346.png)

**Comment by sillypears** [comment]
Ya I broke it after fixing a bunch of other CSS things. Will be fixed eventually.

**Comment by sillypears** [comment]
Did the thing for the thing to fix the thing that was doing the thing

https://github.com/Zamiell/isaac-racing-server/commit/c4d494394ff6c0462e8ee45a3ee058e6512cdac0
